name: ci

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  testing:
    needs: build
    runs-on: ubuntu-22.04
    env:
      retarus_userid: ${{ secrets.RETARUS_USERID }}
      retarus_fax_password: ${{ secrets.RETARUS_FAX_PASSWORD }}
      retarus_customer_number: ${{ secrets.CUSTOMER_NUMBER }}

      retarus_sms_userid: ${{ secrets.RETARUS_USERID }}
      retarus_sms_password: ${{ secrets.RETARUS_SMS_PASSWORD }}
      webexpress_username: ${{ secrets.WEBEXPRESS_USERNAME }}
      webexpress_password: ${{ secrets.WEBEXPRESS_PASSWORD }} 
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
            sharedKey: gh_action_retarus_sdk_rust
      
      - name: run retarus-tests
        run: cargo test --release

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build:
    runs-on: ubuntu-22.04
    needs: testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
          sharedKey: gh_action_retarus_sdk_rust
      - name: build retarus
        run: cargo build --package retarus --release

        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v2
        with:
          path: target/release/.rustc_info.json
          name: ${{ github.sha }}-ci_rust

      