name: fax4app_sdk_rust_pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
          sharedKey: gh_action_retaurs_sdk_rust
      - name: build retarus
        run: cargo build --package retarus --release

  testing:
    needs: build
    runs-on: ubuntu-22.04
    env:
      retarus_userid: ${{ secrets.RETARUS_USERID }}
      retarus_fax_password: ${{ secrets.RETARUS_FAX_PASSWORD }}
      retarus_sms_password: ${{ secrets.RETARUS_SMS_PASSWORD }}
      retarus_customer_number: ${{ secrets.CUSTOMER_NUMBER }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
            sharedKey: gh_action_retaurs_sdk_rust
      
      - name: run retarus-tests
        run: cargo test --release

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  deploy:
    needs: testing
    if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with: 
            sharedKey: gh_action_retaurs_sdk_rust
      - uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_SECRET }}